# Site settings
title: migu's git blog
email: migujeong@gmail.com
baseurl: "/about" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: Have fun!
# Social icons
linkedin: migujeong@gmail.com
github: maigumigu

footer: © Taken theme

# Build settings
markdown: kramdown
