# Site settings
title: migu's git blog
email: migujeong@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: I'm insterested in.. 
<ul>
<li>Java and OOP</li>
<li>Programming Languages</li>
<li>Text mining</li>
<li>Search Engine</li> 
</ul>
# Social icons
linkedin: migujeong@gmail.com
github: maigumigu

footer: © Taken theme

# Build settings
markdown: kramdown
